### ISSUE TITLE
Suggestion to add Polka on Tidelist / CodeFund

### ISSUE THREAD

**Issue by paulocoghi** [lukeed/polka#100]
Hello, Lukeed

Since I believe that there are many developers and companies using your projects, and this tends to grow even more, I would like to share with you two interesting options to generate revenue from them:

https://tidelift.com/about/lifter and https://codefund.io/

Thanks again!

**Comment by lukeed** [comment]
Hey, thanks! :) 

I actually have an [OpenCollective](https://opencollective.com/polka), but I never finished the setup. I don't really like that model tbh. I'm waiting for GitHub Sponsors since it achieves what these 3rd party services try to do – but better.

It's a bit weird to ask for money, so I've never done it. Best to have a funding/donation option built-in to the project repository directly so that a) companies can find it b) skip the awkwardness.

* Codefund doesn't count IMO, since it's developer-targeted and developer-driven ads. Yuck
* Tidelift is trying to promote itself thru OSS outreach. Nothing _wrong_ with that, but it's free marketing for them & developer sustainability/payoff is determined purely by the developers' marketing success.
* OpenCollective is the best of the bunch so far, but, assuming you find a company who _wants_ to support a project, a majority don't because it _is_ "open" – they don't necessarily want to advertise _that_ they're using X, that they're able/willing to financially support anything, and how much they actually gave.

So, I'm sitting here rooting for GitHub Sponsors to go GA – not for personal reasons, but because it can actually solve OSS pain points really really efficiently. 

Closing for now, but thank you for the thought :)
