### ISSUE TITLE
Query an array value

### ISSUE THREAD

**Issue by jiewuza** [lukeed/polka#124]
For express, when querying an array as `value[]=a&value[]=b`, you get `value: ['a', 'b']`.
It helps distinguish between an array and a string when querying an array of lenght 1.
That is,  `value=a` and `value[]=a` results in `value: 'a'` and `value: ['a']`.

But for polka,  it doesnot provide a direct way distinguishing them.
I have to check the type of the value by myself.

**Comment by lukeed** [comment]
Hey there,

Not sure which version you're using, but stable uses the native [`querystring.parse`](https://nodejs.org/dist/latest-v12.x/docs/api/querystring.html#querystring_querystring_parse_str_sep_eq_options) which ignores the key's `[]` and only converts to array on repeat values. The `polka/url@next` (which polka@next uses) emulates this behavior too.

This is the common, safe approach for most platforms. Node.js does it by default, as does `new URL` and `new URLSearchParams` on all browsers and all Node.js versions. The `[]` is part of the key name – values (and value types) are determined by the values themselves.

If you _need_ to copy Express' approach exactly, you can easily add that. Express uses [`qs`](https://www.npmjs.com/package/qs) to create its `req.query` object. You can copy the same behavior wherever you need it or as a custom middleware:

```js
const { parse } = require('qs');

app.get('/foo/bar', (req, res) => {
  let query = {};
  if (req.search && req.search.length > 1) {
    query = parse(req.search.substring(1));
  }
  // ... use 'query' var
})
```

Hope that helps!

**Comment by jiewuza** [comment]
I was using `polka@next`.
But it does not emulates this behavior.

In my route `/q`, I have
```
console.log(req.search, req.query)
```

And when I visit `/my-server-path/q?value[]=test`, I see
```
?value[]=test { 'value[]': 'test'}
```

BTW, I enables `bodyParser.json()` and `bodyParser.raw()` for the server.

**Comment by lukeed** [comment]
I know, that's what I'm saying. By default, the majority of parsers (including browsers) will treat the `[]` as part of the key name. This is why Polka continues to do the same... It's the more generalized behavior.

The behavior you're expecting is custom. If you want that behavior too you must opt into it, as shown above.

---

If it were me, I would just send URLs like `?value=a&value=b`. That's always parsed as an array since `value` repeats: `{ value: ['a', 'b'] }`. It is true that only sending one value will be parsed as a non-array (`{ value: 'a' }`) but that's easily fixed within your server handler:

```js
const values = [].concat(req.query.value || []);
//=> Will always be an array
```

**Comment by jiewuza** [comment]
Oh, I misunderstood you.
Thank you for your instructions.
