### ISSUE TITLE
Swap 'send-type' arguments

### ISSUE THREAD

**Issue by kyusupov33** [lukeed/polka#136]
Perhaps it would be better to swap `code` and `data` arguments for using comfortably =)

Before:
```
const send = require('@polka/send-type');
res.json = send(null, res);
...
res.json(200, payload);
```
After:
```
const send = require('@polka/send-type');
res.json = send(null, res);
...
res.json(payload);
```

Code is 200 by default.

**Comment by lukeed** [comment]
Hey,

It's structured this way because `data` is what's optional for the HTTP response, and a `statusCode` is always required. I understand where you're coming from & tried it for a bit, but in cases where you are sending `204` or want to send the default `Status Text` as a response, it's more awkward to go the other way around.

For what you're doing, you could simply do this:

```js
const sendtype = require('@polka/send-type');

// define once for optimized assignment
function send(res, data, code = 200) {
  sendtype(res, code, data);
}

// ...

res.json = send.bind(null, res);

// ...

res.json(payload);
// or
res.json(payload, 201);
```

Hope that helps!
