### ISSUE TITLE
Feature request: add .static() method

### ISSUE THREAD

**Issue by bmcminn** [lukeed/polka#15]
Express provided a nifty helper for defining a static folder for binary assets, such as styles, images, fonts, etc.

Would be great to have a similar feature, unless this was explicitly left out in order for folks to derive their own.

**Comment by lukeed** [comment]
Hi there! This is intentionally left out. All Express does is expose the `serve-static` dependency ([source](https://github.com/expressjs/express/blob/c0136d8b48dd3526c58b2ad8666fb4b12b55116c/lib/express.js#L80)) &mdash; it's only included to maintain the legacy API.

You can already use `serve-static` with Polka, since it's only a middleware! There's [an example](https://github.com/lukeed/polka/tree/master/examples/with-serve-static), too!

Admittedly, the current usage is a little funky for Express users. A refactor is in the works right now that will change this & make it more familiar for Express veterans:

```js
const serve = require('serve-static')('assets', { ... });

polka()
  .use(serve)
  .get('...', () => {})
```

Closing since I definitely don't want to include this in core. But, a lighter `serve-static` alternative may be on the agenda... I haven't committed one way or another yet 😆

**Comment by bmcminn** [comment]
Good deal, I like that approach, but a getting started guide for express users might be a cool documentation feature.

**Comment by lukeed** [comment]
Yeah, definitely! If the timeline allows it, I want 1.0 to release with a full documentation website too to get people away from a mile-long README.
