### ISSUE TITLE
Feature suggest: Add support for HTTP\2

### ISSUE THREAD

**Issue by Zerotask** [lukeed/polka#162]
It would be great to have HTTP\2 support.

Node.JS already supports it:
https://nodejs.org/dist/latest-v14.x/docs/api/http2.html

**Comment by lukeed** [comment]
Hi there, it's already supported.

Do the exact same thing as the [`https` example](https://github.com/lukeed/polka/blob/master/examples/with-https/index.js), but use the `http2` module instead of the `https` module.

Once you create your own server, you pass it into your (main) Polka instance as `options.server`

Hope that helps~!
