### ISSUE TITLE
How to use it with PassportJS

### ISSUE THREAD

**Issue by ohenepee** [lukeed/polka#20]
For authentication PassportJS requires that something like this is used... but it looks like Polka doesn't support `route-based middlewares`

```
app.post(
  '/login',
  passport.authenticate('local', {
    successRedirect: '/',
    failureRedirect: '/login'
  }),
  (req, res) => {
    // something after the authentication
  }
);
```

**Comment by Youngestdev** [comment]
Hmm.. @lukeed , any plans ?

**Comment by lukeed** [comment]
Hey! Yep, not currently. That's being tracked in #18.

So `passport.authenticate` returns a normal middleware function with the `(req, res, next)` signature. You can call it directly _inside_ the route handler or wrap it with a series of pathname matchers for a global middleware.

This is an example of the first option, which is probably much easier:

```js
let auth = passport.authenticate('local', {...});
app.post('/login', (req, res) => {
  auth(req, res, err => {
    if (err) return onError(res, err); // <~ your own error handler
    // continue with your own stuff
  });
})
```

Hope that helps~! 

_Closing this since the other issue is officially tracking._
