### ISSUE TITLE
Replace `http` with `turbo-http`?

### ISSUE THREAD

**Issue by kurtextrem** [lukeed/polka#37]
I'm not sure if it does something for Polka, but take a look at: https://github.com/mafintosh/turbo-http

**Comment by lukeed** [comment]
Hey,

It wouldn't be replaced, but you could use it instead of native HTTP server. There's a few examples that already show how you can do this with HTTPS server and UWS server. 

In fact, there's a branch here that already has a turbo example. I'll edit with a link when I get to computer.

Be warned though -- turbo is still heavily alpha and doesn't claim (or try) 100% compatibility with Node.js HTTP. This means that a lot of middleware or other http-based packages won't work with it. 

If you're looking to swap, I'd personally go for UWS' http server. It's incomplete, but at least it tries to be compatible. It's also 20k req/s faster on my machine.

**Comment by lukeed** [comment]
Updated with links~! Going to go ahead & close this since there _is_ a way to do this without changing Polka code.

Thanks!

**Comment by kurtextrem** [comment]
Thank you for this great investigation!

**Comment by lukeed** [comment]
No problemo~!

**Comment by DanielSokil** [comment]
@lukeed  What about having a separate branch for `turbo-http`?
`npm install --save polka#turbo`
Or
`npm install --save polka#uws`

**Comment by DanielSokil** [comment]
@lukeed Thank You, I did not know I could do this.

**Comment by lukeed** [comment]
No problem 👍 bummer though, sounds like a documentation problem 😣 Would you say it's because the readme is too long?

**Comment by DanielSokil** [comment]
How did I miss https://github.com/lukeed/polka#optionsserver this!?
The readme is the longest I have ever seen (:
I think grouping by color would help a lot when going through docs: https://stackoverflow.com/a/41247934

**Comment by DanielSokil** [comment]
@lukeed I see you have mentioned `uws` in this issue, but since it has been [depreciated](https://www.npmjs.com/package/uws). I was wondering if you came across [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js)?

When trying it out using polka as a handler, I'm getting this issue:
```bash
/home/danielsokil/Desktop/Lab/Node/uws-demo/node_modules/polka/index.js:72
		let fns=[], arr=this.wares, obj=this.find(req.method, info.pathname);
		                                                           ^

TypeError: Cannot read property 'pathname' of undefined
    at Polka.handler (/home/danielsokil/Desktop/Lab/Node/uws-demo/node_modules/polka/index.js:72:62)
    at uWS.App.any (/home/danielsokil/Desktop/Lab/Node/uws-demo/src/both.js:27:10)
node: ../deps/uv/src/uv-common.c:686: uv_loop_delete: Assertion `err == 0' failed.
Aborted (core dumped)
```

### Here is the demo code:
```JavaScript
const uWS = require('uWebSockets.js');
const polka = require('polka');

const port = 8000;

function one(req, res, next) {
  req.one = true;
  next();
}

function two(req, res, next) {
  req.two = true;
  next();
}

const { handler } = polka()
  .use(one, two)
  .get('/favicon.ico', _ => { })
  .get('/', (req, res) => res.end('Hello'))
  .get('/user/:id', (req, res) => {
    res.end(`User: ${req.params.id}`);
  });

uWS.App({
  /* cert, key and such specified here, or use uWS.App */
}).any('/*', (res, req) => {
  return handler(res, req);
}).listen(port, (token) => {
  if (token) {
    console.log('Listening to port ' + port);
  } else {
    console.log('Failed to listen to port ' + port);
  }
});
```

My conclusion is that `uWebSockets.js` is not compatible with `express` API so they won't be able to work together. Do you think that's the issue?

**Comment by lukeed** [comment]
Hahah, the `taskr` readme is longer :P 
Thanks, good to know~! I'd never seen that before.

Polka will be getting a docs website for its 1.0 – it's WIP now. 

---

It looks like you accidentally swapped `req` and `res` in the handler:

```diff
- return handler(res, req);
+ return handler(req, res);
```

**Comment by DanielSokil** [comment]
I have tried your suggestion, it doesn't resolve the issue.
But I noticed that [handler](https://github.com/lukeed/polka/blob/master/packages/polka/index.js#L70) takes in 3 parameters `req, res, info`, and I only provided 2.

@lukeed Any ideas?

**Comment by lukeed** [comment]
Do you get any errors this time? How does it not work?

TBH, the new `uws` has been on my radar & I really wanna play with it but haven't had time to yet. I know its implementing a custom HTTP engine, so I'm not sure if it's included a 1:1 match of what Polka expects to be in its `IncomingRequest` implementation. 

The third argument [handles itself](https://github.com/lukeed/polka/blob/master/packages/polka/index.js#L71) so that shouldn't be an issue.

**Comment by DanielSokil** [comment]
The error is the same as above:
```bash
/home/danielsokil/Desktop/Lab/Node/uws-demo/node_modules/.registry.npmjs.org/polka/0.5.1/node_modules/polka/index.js:72
		let fns=[], arr=this.wares, obj=this.find(req.method, info.pathname);
		                                                           ^

TypeError: Cannot read property 'pathname' of undefined
    at Polka.handler (/home/danielsokil/Desktop/Lab/Node/uws-demo/node_modules/.registry.npmjs.org/polka/0.5.1/node_modules/polka/index.js:72:62)
    at uWS.App.any (/home/danielsokil/Desktop/Lab/Node/uws-demo/src/both.js:26:28)
node: ../deps/uv/src/uv-common.c:686: uv_loop_delete: Assertion `err == 0' failed.
Aborted (core dumped)
```

**Comment by DanielSokil** [comment]
I have spotted that `@polka/url` requires `req.url`, but `uWS` does not have this API.

**Comment by DanielSokil** [comment]
These are the only `req` methods that I could find in the repo are:
```
req.getMethod()
req.getHeader()
req.getParameter()
req.getUrl()
```
and `res`:
```
res.end()
res.close()
res.onData()
res.onAborted()
res.getWriteOffset()
res.tryEnd()
res.onWritable()
```

**Comment by DanielSokil** [comment]
I have tried `req.url = req.getUrl()` and the server does not crash, but trying any route results in: `Not Found
`

**Comment by lukeed** [comment]
Cool, was going to suggest that. You'll have to add `req.method` support too
