### ISSUE TITLE
Middlewares run in unexpected order

### ISSUE THREAD

**Issue by Rich-Harris** [lukeed/polka#38]
Unexpected to me, anyway 😀 Wanted to raise an issue before attempting a PR, in case this is the desired behaviour.

Repro: https://github.com/Rich-Harris/polka-middleware-order-repro

Essentially, it seems that middlewares without a basepath run before middlewares with one, regardless of the order in which they're added to the app. This means that a generic `app.use(foo)` will take precedence over an earlier `app.use(basepath, serve('assets'))`, which can prevent assets from being served.

**Comment by lukeed** [comment]
Yep yep, this is intentional! There's basically 3 levels that Polka runs through:

1. **Global Middleware** 
    _Those defined without any `basepath` "filter"_

2. **Sub-something Groups**
    _A Polka sub-application or a middleware group to run **only** on paths that begin with `basepath`._

3. **Route handler**
    _The final handler, which is also the most specific route match._

A response can be terminated anywhere along the pipeline, which immediately ends the pipeline too. 

I'm not sure if I forgot that Express was order-dependent for tier handling, or if I never knew that. Either way, I find it much more appealing and useful to dynamically build out an application without necessarily having to do it in a specific order.

> That said, order _does_ matter when writing into global & sub-group arrays.

Another nice thing is that this allow sub-applications to carry _their own_ (relative) global middleware, which makes composing larger applications/services really easy.

There's a [little bit of text](https://github.com/lukeed/polka#handlerreq-res-parsed) that touches on this. Of course, it's incomplete but a WIP Polka documentation site is planned to fix all this.

Lastly, I know this was just a demo repro (thanks!!) but the 404 handler you included is already the default behavior:

```js
.use((req, res) => {
  res.writeHead(404);
  res.end('Not found');
})
```

Polka sends the status code & its `statusText` if no other message body was passed, seen [here](https://github.com/lukeed/polka/blob/master/packages/polka/index.js#L24-L27).

To change the 404 behavior, you'd pass an [`onNoMatch`](https://github.com/lukeed/polka#optionsonnomatch) handler to Polka via `polka({ onNoMatch })` which then gets run [here](https://github.com/lukeed/polka/blob/master/packages/polka/index.js#L82).

**Comment by lukeed** [comment]
Not sure if I fully understand without playing with it. 

You can still mount Sapper as the last global middleware (as done in the [example](https://github.com/lukeed/polka/blob/master/examples/with-sapper/server.js)). And then if a user is using a basepath flag, they can still do the same thing so long as Sapper is calling `next()` when path is not a match.

**Comment by Rich-Harris** [comment]
That's the thing, it doesn't call `next` — it can't, really, because it's responsible for serving 4xx/5xx pages if nothing matches.

Maybe I need to do

```js
app.use(basepath, serve, sapper)
```

rather than

```
app.use(basepath, serve).use(sapper)
```

, and reconfigure the routes accordingly.

**Comment by lukeed** [comment]
Arguably, Sapper should only be handling 4xx-type responses when it's working within its assigned realm. By default (no Sapper-flag basepath), it gets to and should handle everything. But when localized to a certain range of paths, it should only be throwing 4xx's when it's a 400-type _within_ that realm of the application.

Psuedo:

```js
// assume global level by default
const isOwner = config.basepath ? req.path.startsWith(config.basepath) : true;
if (!isOwner) return next(); // not a match

// .. later on, no 'route' found
if (route === void 0) {
  // pass it off to main app logic, not Sapper responsibility
  return isOwner ? sapperError() : next(); 
}
```

**Comment by Rich-Harris** [comment]
Thanks for helping me think this stuff through, by the way 😀 

You're absolutely right, Sapper should only deal with requests pertaining to its basepath. In fact, that insight led me to a [much nicer way of doing things](https://github.com/sveltejs/sapper/pull/200) — now, all you need to do to mount an app on a basepath is this:

```js
polka()
  .use('/my-basepath', serve('assets'), sapper({routes}))
  .listen(PORT);
```

No configuration or environment variables necessary, it just works!

So I'll close this issue rather than continuing to clutter up your tracker. The one thing that does give me pause is that I often order my middlewares to do this sort of thing:

```js
app.use('/requests-that-should-not-be-logged', someMiddleware());
app.use(loggingMiddleware());
```

With Express, requests handled by earlier middlewares don't get handled by later middlewares (unless the earlier middleware wants that to happen, with `next()`), and controlling that is fairly intuitive. If I understand correctly, that's a little harder with Polka? You've spent more time thinking about this than me though, so your way probably makes more sense — I only mention it because it's a potential sticking point for Express refugees.

**Comment by lukeed** [comment]
Great! Happy to help~! And not clutter at all haha

My general recommendation is that if you have a particular exception/filter, that you should manually filter that route from the global scope. That is, of course, assuming you're using an off-the-shelf solution and can't work in the behavior into the middleware directly.

Looking at the [`morgan` logger example](https://github.com/lukeed/polka/blob/master/examples/with-morgan/index.js#L10), you could do something like this:

```js

const logger = morgan('dev'); // instantiate early

polka()
  .use((req, res, next) => {
    return req.url.includes('ignore-this') ? next() : logger(req, res, next);
  })
  .use('/items', require('./items')
  .use('/ignore-this', something())
  // ...
```
