### ISSUE TITLE
Close server gracefully

### ISSUE THREAD

**Issue by icebob** [lukeed/polka#39]
Hi lukeed,

would be good a `close` method which closes the HTTP server gracefully. It should call the [this.server.close()](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_server_close_callback).

**Comment by lukeed** [comment]
Hey~!

I've intentionally left this out for now, since `server.close()` is pretty easy to access & "graceful" has a different meaning to everyone. For example, `server.close` doesn't terminate `Keep-Alive` connections, which (for most) doesn't count qualify as a graceful exit. Handling this behavior correctly is grounds for another library entirely!

If `server.close` is sufficient for you, then I'd roll with that. Otherwise, I'd recommend [`stoppable`](https://github.com/hunterloftis/stoppable):

```js
let app = polka();

let server = stoppable(app.server).listen(PORT, _ => {
  console.log('> READY')
});

// elsewhere

server.stop(err => {
  // stopped -- truly graceful
});
```

**Comment by icebob** [comment]
Thank for info. Currently `server.close` is enough for me. In my case, the aim is that I can call `listen` again after `close`

**Comment by orefalo** [comment]
same issue, tks for the solution
