### ISSUE TITLE
cors

### ISSUE THREAD

**Issue by andymans** [lukeed/polka#47]
cors...ALL the cors. It's the way of the future. Or it would be if it were documented :-)

**Comment by lukeed** [comment]
Polka can't do this for you as it's wildly application specific. You can [manually write them](https://github.com/lukeed/sirv/blob/master/packages/sirv-cli/boot.js#L33-L34) via `res.setHeader` or use third-party, time-tested solutions like [`cors`](https://github.com/expressjs/cors) to handle that for you.

There _is_ [an example using `cors`](https://github.com/lukeed/polka/blob/master/examples/with-firebase-admin/index.js#L10), but it's not the focus of the example since (again) it's wildly app-dependent.

Hope that helps~!
