### ISSUE TITLE
how to add prisma-binding?

### ISSUE THREAD

**Issue by Erkajp** [lukeed/polka#55]

**Comment by lukeed** [comment]
I don't use this or know what it is 😅 If you can point me to a simple Express example I can provide you with an answer

**Comment by Erkajp** [comment]
see [node-graphql-server](https://github.com/graphql-boilerplates/node-graphql-server/blob/master/basic/src/index.js)
see [prisma](https://www.prisma.io/) for info

thanks

**Comment by lukeed** [comment]
By the looks of it, you cant :/

Seems as though [`graphql-yoga`](https://github.com/prismagraphql/graphql-yoga) is a requirement, which is built with Express explicitly. There seems to be no replacing Express or using something instead of `graphql-yoga`.

Sorry, but I don't use this ecosystem at all so I'm of no help here 😞
