### ISSUE TITLE
add json send middleware for response helpers

### ISSUE THREAD

**Issue by itaditya** [lukeed/polka#59]
@lukeed I noticed the response helpers were marked as todo. I believe the most popular response helper is `res.json`. 

I was able to make this work

```js
const jsonSend = (req, res, next) => {
  res.json = (payload) => {
    res.setHeader('Content-Type', 'application/json');
    const jsonResponse = JSON.stringify(payload);
    res.end(jsonResponse);
  }

  next()
}

polka()
  .use(jsonSend)
```

If this looks good, please suggest how we can add this in polka

**Comment by lukeed** [comment]
Hey, there is a [`send-type`](https://github.com/lukeed/polka/tree/master/packages/send-type) package that does this automatically if it receives a data object.

I released it as it as standalone utility so that it it can be used in other frameworks, or never at all. Also, releasing a package as a middleware means it can only be _used_ as a middleware. Releasing as a utility means that this is easily possible:

```js
const polka = require('polka');
const send = require('@polka/send-type');

polka()
  .use((req, res, next) => {
    res.send = send.bind(null, res);
    next();
  })
  // ...
```

Very similar line of thinking 😄 Does that work for you?

**Comment by itaditya** [comment]
Yes sure

**Comment by lukeed** [comment]
Great~!
