### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by ohenepee** [lukeed/polka#69]
Please include benchmarks environment information such as OS, CPU, RAM, Avg/Min/Max CPU & RAM Usage per Framework after multiple runs. Also since most people will be running on Low End Boxes (512MB RAM VPSes) and Embedded Boards like Raspberry Pi, etc... could you add a benchmark with low RAM like 512MB?

Thanks for this awesome library.

Found [this](https://github.com/alexhultman/The-Node.js-performance-palette)

**Comment by DanielSokil** [comment]
Have you seen this: https://github.com/lukeed/polka#benchmarks

**Comment by lukeed** [comment]
Hey, thanks!

Yes, what @DanielSokil linked is correct. There's also a link in that section that points to a benchmarks directory that has more tests across varying Node versions. The numbers there are slightly outdated, but you'll get the gist.

To be honest, it hardly matters. Yes, Polka is a much faster router than Express, Koa, ... etc, but it all goes away once you actually enter your route handler(s). 

For example, routing w/ Polka may take 1ms whereas routing with Express may take 3-7ms (machine dependent, of course). But if the targeted route is running four DB queries in ~400ms, the 2-6ms that Polka saved you is dwarfed.

The other performance metric where Polka outshines others is its resource management. It uses next to no RAM when comparing to an established framework like Express. This is where actual, real-world $$ savings happens, at least in my experience.

It all boils down to getting you from point A to point B as quick as possible, so that time is spent where you expect it to (the destination(s)) and _not_ the journey getting you there. I can't remember the total LOC count now, but it's somewhere around 360 lines _total_ across all dependencies.... that's nothing. Express, Koa, Fastify, etc are juggling so much much and so inevitably they take a little bit longer to get you there.

But again, at the end of the day, the speed isn't where you'll feel the difference in majority of cases. These benchmarks (and any, really) are a measurement of best-case scenarios. Server benchmarks only matter // should only be taken within the context your actual application(s).

I'll end my rant there 🙃 

For reference, these are my machine specs for the main README results. I don't include them because of course it varies from machine-to-machine & consumer hardware specs don't really translate well to server hardware specs.

```
CPU :: 4 GHz Intel Core i7
RAM :: 32 GB 1867 MHz DDR3
```

**Comment by ohenepee** [comment]
Thanks
