### ISSUE TITLE
Missing lockfile for reproducible builds

### ISSUE THREAD

**Issue by DanielRuf** [lukeed/polka#94]
As a developer I want to test previous releases and reproduce the previous builds using a lockfile.

**Comment by jeremyjh** [comment]
Lockfiles are for applications, not for libraries. Library dependencies should be resolved and locked by the user of the library, which gives them control to get security patches and other bug fixes in their transitive dependencies. This is why NPM does not publish package-lock.json files, and supports [shrinkwrap only for applications / CLIs](https://docs.npmjs.com/files/shrinkwrap.json#description).

**Comment by DanielRuf** [comment]
Hi @jeremyjh,

I am very aware of this and I think you have quoted someone who wrote the exact same.

But your answer does not cover my use case. What if we want to clone / fork the repo and use the needed deps which were the latest at the time of each release?

**Comment by guilhermeoc97** [comment]
The only dependency Polka has is `trouter`, and that's another package developed by the same dev. If you need to rollback that one, just skim through the release history and find the release that matches the one on Polka you need. Aside from that, there are only devDependencies used for debugging and nothing else.

Nothing breaks the build as there's basically no build. There's no minifying, no concat, nothing. Just 4 folders that have modules with no dependencies.

The only time you would need a lockfile would be if you wanted to execute the tests with different devDependencies. And to be honest, that doesn't make much sense.

But maybe I'm not able to understand what exactly you need. Can you come up with a scenario where you would need to rollback the devDependencies or the only dependency the package has? Or maybe share the case you're thinking about/having trouble with?

**Comment by DanielRuf** [comment]
> As a developer I want to test previous releases and reproduce the previous builds using a lockfile.

Generally developer = contributor (!= consumer / user). I'm often switching between different NodeJS versions and need reproducible CI / test builds. And this also includes the devDependencies.

You know how everyone does not strictly follow the SemVer rules. I have often seen issues caused by devDependencies too.

If you think that it makes not much sense, then I should probably close the issue. DX, reproducible (CI / test) builds and locked dependencies are very helpful. Especially when some deep dependency of a devDependency might cause issues (see npm shrinkwrap).

**Comment by lukeed** [comment]
Hey,

There's no reason to include a lockfile here. Lockfiles are for applications, not library development. This monorepo already has pinned `devDependencies` _for_ the reason you mentioned – see [here](https://github.com/lukeed/polka/blob/next/package.json#L15-L23). 

Any **dependencies** should always be installed loosely (latest within semver caret ranges) because that's exactly how the library/ies are installed in production. 

Lockfiles in a library, _especially_ in a monorepo setting, are just noise. If there was more complex tooling (or similar) involved, there could be benefit that outweighs the noise, but that's not the case here.

You can easily reproduce my machine environment now, as is.

Hope that helps – sorry I didn't respond sooner~!
